import { format } from 'date-fns'
import type { Finding, Scan } from '../types'

/**
 * Neutralise CSV/Excel formula injection. Scanner findings contain
 * attacker-influenced text (titles/banners from scanned hosts); a value starting
 * with = + - @ or a control char is interpreted as a formula by spreadsheet apps.
 * We prefix such values with a single quote and always quote + escape.
 * See OWASP "CSV Injection".
 */
export function csvCell(value: unknown): string {
  let s = value == null ? '' : String(value)
  if (/^[=+\-@\t\r]/.test(s)) s = "'" + s
  return '"' + s.replace(/"/g, '""') + '"'
}

const CSV_COLUMNS: { header: string; get: (f: Finding) => unknown }[] = [
  { header: 'severity', get: (f) => f.severity },
  { header: 'title', get: (f) => f.title },
  { header: 'asset', get: (f) => f.asset },
  { header: 'port', get: (f) => f.port ?? '' },
  { header: 'service', get: (f) => f.service ?? '' },
  { header: 'cvss', get: (f) => f.cvss ?? '' },
  { header: 'exploitability', get: (f) => f.exploitability ?? '' },
  { header: 'cwe', get: (f) => f.cwe ?? '' },
  { header: 'owasp', get: (f) => f.owasp ?? '' },
  { header: 'source', get: (f) => f.source ?? '' },
  { header: 'recommendation', get: (f) => f.recommendation },
]

export function findingsToCsv(findings: Finding[]): string {
  const header = CSV_COLUMNS.map((c) => c.header).join(',')
  const rows = findings.map((f) => CSV_COLUMNS.map((c) => csvCell(c.get(f))).join(','))
  return [header, ...rows].join('\n')
}

export function findingsToMarkdown(scan: Scan): string {
  let md = `# Spectra Report — ${scan.name}\n\n`
  md += `**Targets:** ${scan.targets.join(', ')}\n**Profile:** ${scan.profile}\n**Date:** ${format(new Date(scan.startedAt), 'PPP')}\n\n`
  md += `## Findings (${scan.findings.length})\n\n`
  scan.findings.forEach((f) => {
    md += `### ${f.severity.toUpperCase()} — ${f.title}\n`
    md += `**Source:** ${f.source || 'unknown'}\n`
    md += `**Asset:** ${f.asset}${f.port ? ':' + f.port : ''} (${f.service || 'unknown'})\n`
    if (f.cve) md += `**CVE:** ${Array.isArray(f.cve) ? f.cve.join(', ') : f.cve}\n`
    if (f.cwe) md += `**CWE:** ${f.cwe}\n`
    md += `**Evidence:** ${f.evidence}\n\n${f.description}\n\n**Recommendation:** ${f.recommendation}\n\n`
    if (f.exploitability) md += `*Exploitability score: ${f.exploitability}*\n\n`
  })
  md += `## Attack Graph Summary\nSee the interactive graph tab in the app for live visual correlation of hosts, services, and vulnerabilities.\n\n`
  md += `_Generated by Spectra._\n`
  return md
}

export type ExportFormat = 'json' | 'csv' | 'md'

export function exportFindings(scan: Scan, fmt: ExportFormat): void {
  let blob: Blob
  let filename = `${scan.name.replace(/\s+/g, '-')}-findings`

  if (fmt === 'json') {
    blob = new Blob([JSON.stringify(scan.findings, null, 2)], { type: 'application/json' })
    filename += '.json'
  } else if (fmt === 'csv') {
    blob = new Blob([findingsToCsv(scan.findings)], { type: 'text/csv' })
    filename += '.csv'
  } else {
    blob = new Blob([findingsToMarkdown(scan)], { type: 'text/markdown' })
    filename += '.md'
  }

  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
